language: node_js
node_js:
  - "10.6.0"
cache:
  directories:
    - "node_modules"
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master

